---

- name: Install Hakyll and git
  apt: name={{ item }}
       state=present
  with_items:
    - libghc-hakyll-dev
    - git
    - make

- name: Check out git head
  git: repo={{ git_repo }}
       dest={{ repo_location }}

- name: Run Makefile
  shell: make publish
  args:
    chdir: "{{ repo_location }}"
  environment:  # Prevent UTF-8 encoding errors
    LANG: "C"
    LC_CTYPE: "en_US.UTF-8"


- name: Symlink _site/ to deploy location
  file: src={{ repo_location }}/_site
        dest={{ deploy_location }}
        state=link
